# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bitcoin',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='etherium',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='litecoin',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
        ),
    ]
