# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180129_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='My Wallet', max_length=200),
        ),
    ]
